# This is a basic workflow to help you get started with Actions

name: 'Homework_1_tests'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - Hw_1
      - Hw_2

  pull_request:
    branches:
      - Hw_1
      - Hw_2
     

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#asdf
#tmp
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
#      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y 
      - run: mkdir gtest
      - run: git clone https://github.com/google/googletest && cd ./googletest && mkdir build && cd ./build && cmake .. -Dgtest_force_shared_crt=ON -DCMAKE_INSTALL_PREFIX=/home/runner/work/otus-cpp-professional/gtest && cmake --build . --target install
      - run: pwd && ls -la && cd ./gtest && ls
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DGTEST_ROOT=/home/runner/work/otus-cpp-professional/gtest
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
