# This is a basic workflow to help you get started with Actions

name: 'Homework_1_tests'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - Hw_1

  pull_request:
    branches:
      - Hw_1
     

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#asdf

