# This is a basic workflow to help you get started with Actions

name: 'Homework_1_tests'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev
     

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#asdf
#tmp
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
#      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y 
      - run: mkdir gtest
      - run: git clone https://github.com/google/googletest && cd ./googletest && mkdir build && cd ./build && cmake .. -Dgtest_force_shared_crt=ON -DCMAKE_INSTALL_PREFIX=/home/runner/work/otus-cpp-professional/gtest && cmake --build . --target install
      - run: pwd && ls -la && cd ./gtest && ls
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DGTEST_ROOT=/home/runner/work/otus-cpp-professional/gtest
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
